In [5]:
import numpy as np

In [6]:
patients_data = np.array([
[45, 80, 200, 120],
[60, 90, 240, 140],
[30, 70, 180, 110],
[50, 85, 220, 130],
[65, 95, 260, 150]
])
patients_data

array([[ 45,  80, 200, 120],
       [ 60,  90, 240, 140],
       [ 30,  70, 180, 110],
       [ 50,  85, 220, 130],
       [ 65,  95, 260, 150]])

In [7]:
data_shape = patients_data.shape
data_shape

(5, 4)

In [8]:
rowNum = data_shape = patients_data.shape[0]
rowNum


5

In [9]:
colNum = data_shape = patients_data.shape[1]
colNum

4

In [10]:
firstPatinet = patients_data[0]
firstPatinet

array([ 45,  80, 200, 120])

In [11]:
age = patients_data[:,0]
age

array([45, 60, 30, 50, 65])

In [12]:
blood_pressure =  patients_data[:,3]
blood_pressure

array([120, 140, 110, 130, 150])

In [13]:
average = np.mean(patients_data)
print(average)

121.0


In [14]:
maximum_heart_rate = np.max(patients_data[:, 1])
print(maximum_heart_rate)

95


In [15]:
minmum_cholesterol = np.min(patients_data[:, 2])
print(minmum_cholesterol)

180


In [16]:
blood_pruser_more_than130=np.where(patients_data[:, -1] > 130)
print(patients_data[blood_pruser_more_than130])

[[ 60  90 240 140]
 [ 65  95 260 150]]


In [17]:
cholesterol_more_than_orequal240 =np.where(patients_data[:, 2] >=240)
print(patients_data[cholesterol_more_than_orequal240])

[[ 60  90 240 140]
 [ 65  95 260 150]]


In [18]:
age_above50 = np.where(patients_data[:, 0] > 50)
print(patients_data[age_above50])

[[ 60  90 240 140]
 [ 65  95 260 150]]


In [26]:
#Q7. Risk Detection (Simple Rule)
cholesterol = np.array([200,240,180,220,260])
pb=np.array([120,140,110,130,150])
high_risk = np.where((cholesterol>140)|(pb>240),"High risk","stable")
print(high_risk)

['High risk' 'High risk' 'High risk' 'High risk' 'High risk']


In [27]:
#Compare Groups
under50 = patients_data[patients_data[:, 0] < 50]
print(under50)
print("\n")
above50 = patients_data[patients_data[:, 0] >= 50]
print(above50)
avg_under50 = np.mean(under50[:, 1])
avg_above50 = np.mean(above50[:, 1])

print("Avg heart rate (under 50):", avg_under50)
print("Avg heart rate (50 and above):", avg_above50)


[[ 45  80 200 120]
 [ 30  70 180 110]]


[[ 60  90 240 140]
 [ 50  85 220 130]
 [ 65  95 260 150]]
Avg heart rate (under 50): 75.0
Avg heart rate (50 and above): 90.0


In [34]:
#Extreme Cases
Highest_blood_pressure = np.max(patients_data[:,3])
print(Highest_blood_pressure)
Lowest_heart_rate =np.min(patients_data[:,1])
print(Lowest_heart_rate)

150
70


In [39]:
# Relationship Thinking
age = patients_data[:, 0]
bp = patients_data[:, 1]
younger_bp = bp[age < 50]
older_bp = bp[age >= 50]

print("Younger avg BP:", np.mean(younger_bp))
print("Older avg BP:", np.mean(older_bp))
print("Older patients show higher average blood pressure than younger ones")

Younger avg BP: 75.0
Older avg BP: 90.0
Older patients show higher average blood pressure than younger ones
